### ISSUE TITLE
xmind打开异常

### ISSUE THREAD

**Issue by Pactortester** [williamfzc/linkediff#1]
- 非常好的工具，发现个问题最后生成的xmind 打不开
>python+mac 运行一切正常
![image](https://user-images.githubusercontent.com/29191106/172835150-4bba30b9-b4ec-4995-929b-955855ccac15.png)

**Comment by williamfzc** [comment]
因为xmind没有官方的sdk，这次用的是这个：
https://github.com/zhuifengshen/xmind

而它已经很久没更新，对新格式的支持有限，用 xmind8 亲测可以打开，新版本则不行
https://www.xmind.cn/xmind8-pro/

**Comment by Pactortester** [comment]
换了xmind版本，已经可以打开了
